name: check_python_version

on:
  push:
    branches:
      - main

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
      - name: Konfiguracja Pythona
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Aktualizacja pip
        run: |
          python -m pip install --upgrade pip

      - name: Wyświetlenie wersji Pythona
        run: python --version

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
