name: main

on:
  push:
    branches:
      - main

jobs:
  main-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "pypy3.9", "pypy3.10"]
    exclude:
      - os: macos-latest
        python-version: "3.9"

    steps:
      - name: Konfiguracja Pythona
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Aktualizacja pip
        run: |
          python -m pip install --upgrade pip

      - name: Instalacja flake8 i unittest
        run: |
          python -m pip install flake8
          python -m pip install unittest

      - name: Wyświetlenie wersji Pythona
        run: python --version

      - name: Uruchomienie flake8
        run: flake8 .

      - name: Uruchomienie unittest
        run: python -m unittest discover -s tests -p '*.py'
